version: '2.3'

services:
    front:
        image: cookiespoc/front
        container_name: front
        tty: true # Needed to ensure container doesn't self terminate
        build:
            context: ./front
            dockerfile: Dockerfile
        environment:
            - HOST_BACK=http://back:4000
        ports: 
            - '5000:5000' # host:container
        links:
            - "back"
        networks:
            - mynetwork
    back:
        image: cookiespoc/back
        container_name: back
        tty: true # Needed to ensure container doesn't self terminate
        build:
            context: ./back
            dockerfile: Dockerfile
        ports:
            - '4000:4000' # host:container
        networks:
            - mynetwork
networks:
    mynetwork:
        name: mynetwork
        driver: bridge
